---
- name: Deploy Calculator App with Docker
  hosts: webserver
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Pull Docker Image
      command: docker pull mydockerhub/calculator-app:latest

    - name: Run Docker Container
      command: docker run -d --name calculator-app mydockerhub/calculator-app:latest
